# image will be published to ghcr.io/<user>/<name>
name: my-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - virt-manager
      - https://github.com/arturasb/my-silverblue/raw/eaf3af34502715749e5108cb0289ae9299cfb30b/files/rpm-packages/homed-selinux-1.0-1.fc38.noarch.rpm
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
    user:
      # repo-name will overwrite the previously-configured repo-name for the user remote
      repo-name: flathub-user
      repo-title: "Flathub (User)"
      install:
      - com.github.tchx84.Flatseal
      - de.haeckerfelix.Fragments
      - io.freetubeapp.FreeTube
      - org.keepassxc.KeePassXC
      - org.mozilla.Thunderbird
      - org.mozilla.firefox
      - org.telegram.desktop
      - org.libreoffice.LibreOffice
      - org.gnome.Connections
      - io.github.celluloid_player.Celluloid
      - com.usebottles.bottles
      - org.gnome.Boxes
      - com.mattjakeman.ExtensionManager
      - org.gnome.Connections
      - org.gnome.Calendar
      - org.gnome.Contacts
      - org.gnome.Geary
      - org.gnome.Calculator
      - org.gnome.TextEditor
      - org.fedoraproject.MediaWriter
      - org.gnome.Logs
      - com.github.wwmm.easyeffects
  - type: gnome-extensions
    install:
    - GSConnect
    - 615 # AppIndicator
  - type: gschema-overrides
    include:
    - zz1-mysettings.gschema.override

  - type: systemd
    # this example disables
    system:
      enabled:
        - libvirt-workaround.service
        - libvirt-group.service
        - homed-selinux-workaround.service
        - homed-authselect-workaround.service
        - swtpm-workaround.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

