# image will be published to ghcr.io/<user>/<name>
name: my-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
     - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo # when including COPR repos, use the %OS_VERSION% magic string
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
    install:
      - libvirt-daemon-driver-network
      - libvirt-daemon-driver-nodedev
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-storage-core
      - qemu-audio-spice
      - qemu-char-spice
      - qemu-device-display-qxl
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-system-x86-core
      - virt-manager

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      repo-name: flathub
      repo-title: "Flatpak (User)"
      install:
      #- org.virt_manager.virt-manager
      - com.github.tchx84.Flatseal
      - de.haeckerfelix.Fragments
      - io.freetubeapp.FreeTube
      - org.keepassxc.KeePassXC
      - org.mozilla.Thunderbird
      - org.mozilla.firefox
      - org.telegram.desktop
      - org.libreoffice.LibreOffice
      - org.gnome.Connections
      - io.github.celluloid_player.Celluloid
      - com.usebottles.bottles
      - org.gnome.Boxes
      - com.mattjakeman.ExtensionManager
      - org.gnome.Connections
      - org.gnome.Calendar
      - org.gnome.Contacts
      - org.gnome.Geary
      - org.gnome.Calculator
      - org.gnome.TextEditor
      - org.fedoraproject.MediaWriter
      - org.gnome.Logs
      - com.github.wwmm.easyeffects

  - type: gnome-extensions
    install:
    - GSConnect
    - 615 # AppIndicator
  - type: gschema-overrides
    include:
    - zz1-mysettings.gschema.override

  - type: systemd
    system:
      enabled:
      - homed-authselect-workaround.service
      - virtnetworkd.service
      - virtqemud.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

