#!/usr/bin/env bash

# SCRIPT VERSION
SWTPM_FIX_VER=1
SWTPM_FIX_VER_FILE="/etc/my-workarounds/swtpm-fix"
SWTPM_FIX_VER_RAN=$(cat "$SWTPM_FIX_VER_FILE")

# Run script if updated
if [[ -f $SWTPM_FIX_VER_FILE && "$SWTPM_FIX_VER" = "$SWTPM_FIX_VER_RAN" ]]; then
  echo "Homed swtpm fix has already run. Exiting..."
  exit 0
fi

# Fix SELinux contexts for swtpm executables
# Mounting /usr RW to set SELinux contexts
/usr/bin/mount -o remount,rw /usr
# Fix swtpm contexts
/usr/sbin/restorecon -rv /usr/bin/swtpm

# Create missing swtpm-localca directory
/usr/bin/mkdir /var/lib/swtpm-localca
# Fix ownership of swtpm-localca directory
/usr/bin/chown tss /var/lib/swtpm-localca

echo "It is recommended to reboot system now in order to remount /usr RO."

# Prevent future executions
echo "Writing state file"
echo "$SWTPM_FIX_VER" > "$SWTPM_FIX_VER_FILE"
